spring:
  application:
    name: sep-2023-java-spring
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgres://localhost:5433"
    username: "product-service-db-user"
    password: "product-service-db-password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  data:
    mongodb:
      uri: ${mongodb.uri}
      database: "product_reviews"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  sender:
    username: "eduardokten@gmail.com"

jwt:
  secret: super-secret-word-with-letters-and-numbers-0-1-2-3-4-5-6-7-8-9
  access-token:
    ttl-millis: 3600000
  refresh-token:
    ttl-millis: 360000000

logging:
  level:
    org:
      springframework:
        security: DEBUG
