spring:
  application:
    name: sep-2023-java-spring
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgres://localhost:5433"
    username: "product-service-db-user"
    password: "product-service-db-password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  data:
    mongodb:
      uri: ${mongodb.uri}
      database: "product_reviews"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  sender:
    username: ${mail.sender}